### ISSUE TITLE
算法效果

### ISSUE THREAD

**Issue by ASONG0506** [JunjieLiuSWU/LaneDetection_End2End#1]
哈喽，请问你有自己训练过本算法或者有一些改进的方法尝试过吗，就是这个算法在一些其他的数据表现比较糟糕，如下图
![image](https://user-images.githubusercontent.com/26050577/135862130-7428ee23-d4dc-43be-b6d1-4ea2b73d40c5.png)
![image](https://user-images.githubusercontent.com/26050577/135862262-0b3ae76a-2dad-4eb8-8853-651fead84f75.png)
求交流！谢谢！

**Comment by JunjieLiuSWU** [comment]
抱歉，并没有尝试过其他改进，目前主要研究方向是３Ｄ感知，如果有这方面的问题欢迎交流.

Asong ***@***.***> 于2021年10月4日周一 下午9:44写道：
